model_dir: /Users/wangfangyuan/opt/ML/save
  # In milliseconds. 24 hours
time_window: 86400000
min_updates: 1000
layer_index: 3
server:
  port: 9997

spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
